### ISSUE TITLE
Behaviour of `pdb_selres`

### ISSUE THREAD

**Issue by TianyiShi2001** [haddocking/pdb-tools#116]
**Describe the bug**

`pdb_selres` does not seem to handle `TER` records correctly, as it tries to read a residue ID from that line, which usually does not exist.

**To Reproduce**

Here's a simple PDB file with 3 residues (generated by pdb_splitmodel):

```
ATOM      1  N   MET     1      88.820 110.610  35.000  1.00  0.00           N
ATOM      2  H1  MET     1      89.440 110.390  34.230  1.00  0.00           H
ATOM      3  H2  MET     1      88.400 109.720  35.230  1.00  0.00           H
ATOM      4  H3  MET     1      88.080 111.180  34.620  1.00  0.00           H
ATOM      5  CA  MET     1      89.410 111.440  36.040  1.00  0.00           C
ATOM      6  HA  MET     1      90.140 110.860  36.600  1.00  0.00           H
ATOM      7  CB  MET     1      90.100 112.650  35.480  1.00  0.00           C
ATOM      8  HB1 MET     1      90.510 113.180  36.340  1.00  0.00           H
ATOM      9  HB2 MET     1      89.370 113.290  34.970  1.00  0.00           H
ATOM     10  CG  MET     1      91.360 112.190  34.580  1.00  0.00           C
ATOM     11  HG1 MET     1      90.960 111.610  33.750  1.00  0.00           H
ATOM     12  HG2 MET     1      92.050 111.550  35.130  1.00  0.00           H
ATOM     13  SD  MET     1      92.140 113.680  33.900  1.00  0.00           S
ATOM     14  CE  MET     1      90.970 114.080  32.520  1.00  0.00           C
ATOM     15  HE1 MET     1      91.180 113.430  31.670  1.00  0.00           H
ATOM     16  HE2 MET     1      89.950 113.980  32.920  1.00  0.00           H
ATOM     17  HE3 MET     1      91.180 115.130  32.320  1.00  0.00           H
ATOM     18  C   MET     1      88.240 111.850  36.910  1.00  0.00           C
ATOM     19  O   MET     1      87.340 112.580  36.460  1.00  0.00           O
ATOM     20  N   SER     2      88.210 111.490  38.240  1.00  0.00           N
ATOM     21  H   SER     2      89.070 111.170  38.660  1.00  0.00           H
ATOM     22  CA  SER     2      87.080 111.510  39.150  1.00  0.00           C
ATOM     23  HA  SER     2      86.440 112.270  38.690  1.00  0.00           H
ATOM     24  CB  SER     2      86.330 110.190  39.160  1.00  0.00           C
ATOM     25  HB1 SER     2      86.200 109.900  38.110  1.00  0.00           H
ATOM     26  HB2 SER     2      85.400 110.380  39.690  1.00  0.00           H
ATOM     27  OG  SER     2      87.050 109.250  39.940  1.00  0.00           O
ATOM     28  HG  SER     2      86.460 108.980  40.660  1.00  0.00           H
ATOM     29  C   SER     2      87.350 112.030  40.610  1.00  0.00           C
ATOM     30  O   SER     2      86.340 112.090  41.310  1.00  0.00           O
ATOM     31  N   VAL     3      88.520 112.490  41.030  1.00  0.00           N
ATOM     32  H   VAL     3      89.340 112.490  40.440  1.00  0.00           H
ATOM     33  CA  VAL     3      88.810 112.900  42.440  1.00  0.00           C
ATOM     34  HA  VAL     3      88.050 112.530  43.120  1.00  0.00           H
ATOM     35  CB  VAL     3      90.170 112.290  42.880  1.00  0.00           C
ATOM     36  HB  VAL     3      90.240 112.470  43.950  1.00  0.00           H
ATOM     37  CG1 VAL     3      90.300 110.780  42.690  1.00  0.00           C
ATOM     38 1HG1 VAL     3      89.930 110.380  41.750  1.00  0.00           H
ATOM     39 2HG1 VAL     3      91.330 110.460  42.830  1.00  0.00           H
ATOM     40 3HG1 VAL     3      89.790 110.330  43.550  1.00  0.00           H
ATOM     41  CG2 VAL     3      91.310 112.920  42.070  1.00  0.00           C
ATOM     42 1HG2 VAL     3      92.300 112.640  42.410  1.00  0.00           H
ATOM     43 2HG2 VAL     3      91.250 112.810  40.990  1.00  0.00           H
ATOM     44 3HG2 VAL     3      91.280 114.000  42.250  1.00  0.00           H
ATOM     45  C   VAL     3      88.770 114.420  42.520  1.00  0.00           C
ATOM     46  O   VAL     3      88.910 115.210  41.610  1.00  0.00           O
TER
```

```
pdb_selres -1:2 foo.pdb
```

gives:

```
Traceback (most recent call last):
  File "/home/tianyi/miniconda3/bin/pdb_selres", line 8, in <module>
    sys.exit(main())
  File "/home/tianyi/miniconda3/lib/python3.9/site-packages/pdbtools/pdb_selres.py", line 249, in main
    pdbfh, resrange = check_input(sys.argv[1:])
  File "/home/tianyi/miniconda3/lib/python3.9/site-packages/pdbtools/pdb_selres.py", line 188, in check_input
    resid_list.append(int(line[22:26]))
ValueError: invalid literal for int() with base 10: ''

```

**Expected behavior**

Should select residues 1 and 2.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python Version: 3.9.5

**Comment by TianyiShi2001** [comment]
A possible fix might be changing 

https://github.com/haddocking/pdb-tools/blob/2fecdebd7520505b68ab515c54fa7c128e7a8090/pdbtools/pdb_selres.py#L180-L188

to

```python
    records = ('ATOM', 'HETATM', 'ANISOU')
    prev_res = None
    for line in fh:
        if line.startswith('TER'):
            break
        if line.startswith(records):
            res_id = line[21:26]  # include chain ID
            if res_id != prev_res:
                prev_res = res_id
                resid_list.append(int(line[22:26]))
        buffer = iter_chain(buffer, [line])
```

**Comment by TianyiShi2001** [comment]
It turns out that [gromacs trjconv](https://manual.gromacs.org/documentation/5.1/onlinehelp/gmx-trjconv.html) is the culprit as it produces concatenated PDB files with `TER` records not adhering to the standard (it writes `TER` only, without writing chain and residue IDs, and this can be fixed by `pdb_tidy`)
