### ISSUE TITLE
CIF to PDB: issue in pdb_fromcif for predicted structures

### ISSUE THREAD

**Issue by venzera** [haddocking/pdb-tools#168]
Hi! 

When i use pdb_fromcif.py it gets: 
`Traceback (most recent call last):
  File "pdb_fromcif.py", line 261, in <module>
    main()
  File "pdb_fromcif.py", line 240, in main
    for lineno, line in enumerate(new_pdb):
  File "pdb_fromcif.py", line 179, in run
    charge = fields[labels.get('_atom_site.pdbx_formal_charge')]
             ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType`

There is no charge fields in cif files resulted from Chai-1 or AF3 predictions (maybe in all cif files in general, idk). 
It can be solved by simply removing lines 179-184: 
`            charge = fields[labels.get('_atom_site.pdbx_formal_charge')]
            try:
                charge = charge
            except ValueError:
                charge = '  '
`
and changing line 187 from `atom_line = _a.format(record, serial, atname, altloc, resname,                                  chainid, resnum, icode, x, y, z, occ, bfactor, segid, element, charge)` into 'atom_line = _a.format(record, serial, atname, altloc, resname, chainid, resnum, icode, x, y, z, occ, bfactor, segid, element)'

I hope it will be useful, since most of the tools still require pdb format. 
Sorry, if it is mentioned before.

**Comment by callum-b** [comment]
Hi,
I'm getting the same issue with an AF3 prediction. It could be nice to maybe try to get the charge from the CIF if it exists, but not fail if it isn't present, seeing as AF3 doesn't use it.
Best,
Cal

**Comment by rvhonorato** [comment]
Thank you for reporting the issue and thanks @amjjbonvin for patching it.

Fix has been merged and is available in `v2.6.1` -> `pip install --upgrade pdb-tools`

**Comment by camilogarciabotero** [comment]
Thanks!
